import { StyleSheet } from "react-native";
import { height, width } from "../Dimensions";

const LogoAndNameOneContainer = {flexDirection:'row',
  alignItems:'center',
  justifyContent:'center'}
const TeamCodeOne = {fontFamily:'Poppins-Medium',
  fontSize:15,
  color:'#ffffff'}
const common = {  flexDirection:'row',
  justifyContent:'space-between',
  alignItems:'center'}
const styles = StyleSheet.create({
  MainDetailsContainer: {
    backgroundColor: '#1a1a1a',
    height: 140,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  LogoAndnameContainer: {
    ...LogoAndNameOneContainer,
    marginTop: 17,
  },
  LogoAndNameOneContainer: {
    ...LogoAndNameOneContainer,
    marginRight: 20,
  },
  LogoAndNameTwoContainer: {
    ...LogoAndNameOneContainer,
    marginLeft: 20,
  },
  TeamCodeOne: {
    ...TeamCodeOne,
    marginLeft: 3,
  },
  TeamCodeTwo: {
    ...TeamCodeOne,
    marginRight: 3,
  },
  versustext: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
  },
  TeamLogoOne: {
    width: 43,
    height: 43,
  },
  TWholeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  BallLeftMainContainer: {
    marginTop: 17,
    marginBottom: -8,
  },
  BallsLeftBallsText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    color:'#ababab'
  },
  BallsLeftBallsMainText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14.5,
    color: '#f6f7fb',
    position: 'relative',
    bottom: 1.5,
  },
  OverNamePattiContainer: {
    ...common,
    paddingVertical: 4,
    paddingHorizontal: 12,
    backgroundColor: '#ffffff',
    borderBottomWidth: 0.7,
    borderBottomColor: '#e8e8e8',
    elevation: 2,
  },
  CreateSetText: {
    color: '#1a1a1a',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
  },
  PikersMainSuperContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 90,
    marginHorizontal: 10,
  },
  PickerContainer: {
    ...common,
    backgroundColor: '#fffffe',
    borderColor: '#d4d4d4',
    borderWidth: 0.6,
    borderRadius: 11,
    paddingHorizontal: 12,
    marginBottom: 20,
    width: '92%',
    elevation: 0.5,
  },
  ModalMainContainer: {
    maxHeight: 0.9 * height,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingTop: 10,
    borderColor: '#a1a1a1',
    borderWidth: 0.4,
    opacity: 0.99,
  },
  SelectScoreText: {
    color: '#1a1a1a',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
    fontSize: 15,
  },
  BallNumberingText: {
    color: '#9d9d9d',
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    paddingRight: '5%',
  },
  BallNameText: {
    color: '#545454',
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
  },
  ScoreItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 0.6,
    borderBottomColor: '#e6e6e6',
    borderBottomEndRadius: 11,
    borderBottomStartRadius: 11,
    padding: 5,
  },
  ScoreDesignContainer: {
    ...LogoAndNameOneContainer,
    paddingLeft: 10,
    width: '80%',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  NextButtonText: {
    position: 'absolute',
    bottom: 25,
    color: 'white',
    backgroundColor: '#999999',
    borderRadius: 25,
    fontFamily: 'Poppins-SemiBold',
    fontSize: 17,
    paddingVertical: 7,
    paddingHorizontal: 30,
    alignSelf: 'center',
    elevation: 2,
  },
  TabPattiItemContainer2: {
    minWidth: 37,
    height: 28,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 1,
    borderRadius: 4,
  },
  TabPattiText2: {
    color: '#f6f7fb',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
  },
  BallNumberingText0: {
    fontFamily: 'Poppins-Medium',
    fontSize: 7,
    position: 'absolute',
    bottom: 16.8,
    right: 31,
  },
  ActivityIndicator: {
    position: 'absolute',
    height: height,
    width: width,
    // bottom: 12,
    backgroundColor: '#f6f7fb',
  },
  ChooseText: {
    fontSize: 16,
    color: '#121212',
    fontFamily: 'Poppins-SemiBold',
    textAlign: 'center',
  },
  ChooseHeadingsContainer: {
    borderTopWidth: 0.5,
    ...common,
    paddingHorizontal: 12,
    borderBottomWidth: 0.5,
    borderColor: '#a1a1a1',
    paddingVertical: 4,
  },
  ChooseHeadings: {
    color: '#8d8d8d',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
  },
  PickerContainer2: {
    ...common,
    backgroundColor: '#fffffe',
    borderBottomColor: '#f2f2f2',
    borderBottomWidth: 1,
    width: '100%',
    backgroundColor: '#ffffff',
  },
  StarBonusCircle: {
    fontSize: 14,
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 7,
    fontWeight: '600',
  },
});

export default styles;